language: cpp
compiler: gcc
sudo: false

addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - clang
      - doxygen
      - valgrind
      - libgtest-dev
      - libboost-dev

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++-4.8 --version 2>&1 | grep g++-4.8
    - dpkg -l libgtest-dev | grep libgtest
    - gcov-4.6 --version | grep gcov
    - gcov-4.8 --version | grep gcov
    - valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version

script:
    - date
    - ls -al
    - make Graph.log
    - make graph-tests
    - ls -al
    - make html
    - ls -al
    - make test
    - make clean
    - make test CXX=clang++
    - ls -al
    - make check